### PR TITLE
updated certificate creation section

### PR DESCRIPTION
**Pull request by megamorf**
Fixed a few things and made it clear that there are two approaches to the certificate creation process.
I was about to change the LM\Root store to LM\My but you already did that. I was wondering why it was there in the first place. heh :-)

Let me know what you think.

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/powershell-docs/1)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Nice work @megamorf! Thank you very much for helping with this one. It's one of the fiddlier side of DSC for sure! Especially with the whole Nano Server thing thrown into the mix (I've spent days and days now nailing down the credential encryption process with DSC on Nano server - I hope it improves before final release).

You know what needs to be added some day? SecureMOF with a PKI :) But I'll leave that for another document entirely!

**Comment by megamorf** [comment]
Heh, I'm about to implement a PKI based on DSC in our company. That means I'll have to change everything to PKI certifcates after the setup. We could collaborate on the PKI docs if you want :-)

**Comment by PlagueHO** [comment]
Yep, I'd definitely be keen for that. I think that would be a great idea :smile: When you're ready to get going on it (good luck BTW :) ) we could raise in issue in the PowerShell-docs repo letting them know the plan and go from there. The issue could be the location for discussion.

**Comment by PlagueHO** [comment]
This is actually one of the items on Travis' list of documents he thinks we should write - in this issue:
https://github.com/PowerShell/DscResources/issues/87

**Comment by megamorf** [comment]
Sure thing, let's use that one :-)

**Comment by PlagueHO** [comment]
Cool. I've tagged you in the Issue from Travis' and let him know what we're planning.

**Pull request merged**
